version: "3.9"
services:
  api:
    build: .
    container_name: shopsquire_api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    command: ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8080"]

  db:
    image: postgres:16
    container_name: shopsquire_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shopsquire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shopsquire_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
