"""Generate deployable dependency profiles from Poetry's authoritative lock."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from collections import deque
from pathlib import Path
from typing import Any

from packaging.markers import Marker, default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "poetry.lock"
PROFILES = ROOT / "config" / "runtime_dependency_profiles.json"
TARGET_ENV = {
    **default_environment(),
    "python_version": "3.11",
    "python_full_version": "3.11.0",
    "sys_platform": "linux",
    "platform_system": "Linux",
    "platform_python_implementation": "CPython",
}


def _marker_applies(
    expression: str | dict[str, str] | None, *, extras: set[str] | None = None,
) -> bool:
    if not expression:
        return True
    if isinstance(expression, dict):
        expression = expression.get("main")
        if not expression:
            return False
    if expression == "<empty>":
        return True
    marker = Marker(expression)
    candidates = extras or {""}
    return any(marker.evaluate({**TARGET_ENV, "extra": extra}) for extra in candidates)


def _dependency_options(value: Any) -> list[dict[str, Any]]:
    raw = value if isinstance(value, list) else [value]
    return [item if isinstance(item, dict) else {"version": item} for item in raw]


def _locked_packages() -> tuple[dict[str, dict[str, Any]], str]:
    raw = LOCK.read_bytes()
    body = tomllib.loads(raw.decode("utf-8"))
    packages: dict[str, dict[str, Any]] = {}
    for package in body["package"]:
        name = canonicalize_name(package["name"])
        if not _marker_applies(package.get("markers")):
            continue
        existing = packages.get(name)
        if existing is not None and existing["version"] != package["version"]:
            raise RuntimeError(f"ambiguous locked versions for {name}")
        packages[name] = package
    return packages, hashlib.sha256(raw).hexdigest()


def _root_requirement(value: str) -> Requirement:
    return Requirement(value)


def _closure(roots: list[str], packages: dict[str, dict[str, Any]]) -> list[str]:
    requested_extras: dict[str, set[str]] = {}
    queue: deque[str] = deque()

    def enqueue(name: str, extras: set[str] | None = None) -> None:
        canonical = canonicalize_name(name)
        if canonical not in packages:
            raise RuntimeError(f"{canonical} is not present in poetry.lock")
        previous = requested_extras.setdefault(canonical, set())
        new = set(extras or ()) - previous
        if canonical not in queue and (new or not previous):
            previous.update(new)
            queue.append(canonical)

    for raw in roots:
        requirement = _root_requirement(raw)
        enqueue(requirement.name, set(requirement.extras))

    visited_extras: dict[str, frozenset[str]] = {}
    while queue:
        name = queue.popleft()
        package = packages[name]
        extras = requested_extras[name]
        signature = frozenset(extras)
        if visited_extras.get(name) == signature:
            continue
        visited_extras[name] = signature

        for dependency, value in (package.get("dependencies") or {}).items():
            options = _dependency_options(value)
            applicable = [
                option for option in options
                if not option.get("optional")
                and _marker_applies(option.get("markers"), extras=extras)
            ]
            if applicable:
                child_extras = {
                    extra
                    for option in applicable
                    for extra in option.get("extras", [])
                }
                enqueue(dependency, child_extras)

        for extra in extras:
            for raw_requirement in (package.get("extras") or {}).get(extra, []):
                requirement = Requirement(raw_requirement)
                if requirement.marker and not requirement.marker.evaluate(
                    {**TARGET_ENV, "extra": extra}
                ):
                    continue
                enqueue(requirement.name, set(requirement.extras))

    return sorted(requested_extras)


def _render(profile: str, roots: list[str], packages: dict[str, dict[str, Any]], lock_hash: str) -> str:
    names = _closure(roots, packages)
    lines = [
        "# Generated by scripts/generate_runtime_requirements.py; do not edit.",
        f"# profile: {profile}",
        f"# poetry.lock sha256: {lock_hash}",
    ]
    lines.extend(f"{name}=={packages[name]['version']}" for name in names)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--profile", action="append", default=[])
    args = parser.parse_args()
    definitions = json.loads(PROFILES.read_text(encoding="utf-8"))
    selected = args.profile or list(definitions)
    unknown = sorted(set(selected) - set(definitions))
    if unknown:
        raise SystemExit(f"unknown runtime profiles: {', '.join(unknown)}")
    packages, lock_hash = _locked_packages()
    stale: list[str] = []
    for profile in selected:
        definition = definitions[profile]
        output = ROOT / definition["output"]
        rendered = _render(profile, definition["roots"], packages, lock_hash)
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != rendered:
                stale.append(output.relative_to(ROOT).as_posix())
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(rendered, encoding="utf-8", newline="\n")
            print(output.relative_to(ROOT).as_posix())
    if stale:
        print("stale runtime requirements: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
