$env:EXTERNAL_RESEARCH_ENABLED = "1"
$env:EXTERNAL_RESEARCH_SEARCH_URL = "http://127.0.0.1:8888/search?q={query}&format=json"
$env:EXTERNAL_RESEARCH_ALLOW_PRIVATE = "1"
$env:EXTERNAL_RESEARCH_LOCAL_PROOF_ENROLLED = "1"
$env:EXTERNAL_RESEARCH_PROVIDER_ID = "local_searxng"
$env:EXTERNAL_RESEARCH_PROVIDER_BILLING_CLASS = "free"
$env:OFFICIAL_REQUIREMENTS_API_URL = "http://127.0.0.1:8099/requirements?q={query}"
$env:OFFICIAL_REQUIREMENTS_DOMAIN_ALLOWLIST = "docs.vendor.example"
$env:EXTERNAL_RESEARCH_TENANT_ALLOWLIST = "default"
$env:EXTERNAL_RESEARCH_SOURCE_REVIEWED_BY = "e2e-source-policy-reviewer"
$env:EXTERNAL_RESEARCH_SOURCE_LICENCE = "test-fixture"
$env:PORTFOLIO_DEMO_INVENTORY_PROFILE = "realistic"

& (Join-Path $PSScriptRoot "..\start_demo.ps1")
