"""
Autogenerated Alembic revision script.
"""
from alembic import op
import sqlalchemy as sa

revision = '${up_revision}'
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}

def upgrade():
% if upgrades:
${upgrades}
% else:
    pass
% endif

def downgrade():
% if downgrades:
${downgrades}
% else:
    pass
% endif